# Data
```{r subset-data}
rm(list=ls())
dataDIR <- '~/work/data/dcas/dcas2016/'
load(paste0(dataDIR,'Dataset/R/DCAS_2016_weighted.Rdata'))
texcmds <- list()

dcas$quad <- dcas$neighborhood=='Global Neighborhood'
table(dcas[,c('neighborhood','quad')])
N_norace <- sum(is.na(dcas$dem.race) & dcas$quad==TRUE)
dcas <- dcas[!is.na(dcas$dem.race) & dcas$quad==TRUE,]
dcas$sample_tract <- droplevels(dcas$sample_tract)
# dcas$sample_tract <- relevel(dcas$sample_tract, ref="51059452600")
N_quad <- length(dcas$studycase)
N <- sum(!is.na(dcas$dem.race))
texcmds[['N']] <- N
```


```{r quad-all-comparison}
source('dcarea/make-quad-nonquad-comparison-table.R')
```

```{r quad-table, echo=TRUE, include=TRUE}
kable(quad_tbl, row.names = FALSE)
```

```{r dependent-variables}
dcas$satisfied <- dcas$nhd.satisfaction %in% c(
                       'Extremely satisfied','Very satisfied')*1
table(dcas[, c('nhd.satisfaction','satisfied')])
dcas$extremely_satisfied <- as.numeric(dcas$nhd.satisfaction=='Extremely satisfied')*1
table(dcas[, c('nhd.satisfaction','extremely_satisfied')])

dcas$better <- dcas$nhd.change %in% c(
                       'Much better', 'Somewhat better')*1
table(dcas[, c('nhd.change','better')])
dcas$much_better <- (dcas$nhd.change=='Much better')*1
table(dcas[, c('nhd.change','much_better')])
```



<!-- ## Preferences for Other Communities -->
```{r rename-commvars}
## Change names to have search dimension first and commname second
## Help on regex part: https://stackoverflow.com/questions/952275/regex-group-capture-in-r-with-multiple-capture-groups
# search.vars <- grep('nhd\\.srch.+\\.', names(dcas), value=TRUE)
# new_search_matches <- regmatches(
#     search.vars, regexec('nhd\\.srch\\.(.+)\\.(.+)$', search.vars))
# new_search_names <- sapply(new_search_matches, function(x){
#     paste(rev(x[2:3]), collapse='_')})
# names(dcas)[names(dcas)%in%search.vars] <- new_search_names
# 
# dcas$consider_num <- rowSums(dcas[grep('^cons_', names(dcas))])
# dcas$consider_any <- dcas$consider_num > 0
# dcas$notconsider_num <- rowSums(dcas[grep('^nc_', names(dcas))])
# dcas$notconsider_any <- dcas$notconsider_num >0
```



```{r independent-variables}
table(dcas$dem.race, useNA='always')
dcas$dem.race <- relevel(dcas$dem.race, ref='white')
```





```{r demographic-variables}

dcas$age <- dcas$dem.age - 50 ## Center at age 50
dcas$forborn <- dcas$dem.forborn
dcas$man <- dcas$dem.gender.mf=='Male'
dcas$kids <- as.numeric(as.character(dcas$q2)) > 0
dcas$kids[as.numeric(as.character(dcas$q2)) > 90] <- NA
dcas$married <- grepl("Now married", dcas$dem.marital.stat)
table(dcas[,c('dem.marital.stat','married')]) ##Check recoding
```

```{r economic-variables}
dcas$educ <- factor(dcas$dem.educ.attain, order=FALSE) %>% 
                relevel(ref='H.S.')
educ_dummies <- paste0('educ',1:5)
dcas[,educ_dummies] <- lapply(1:5,
        function(i) {unclass(dcas$dem.educ.attain)==i})
for(i in 1:5) { ##Check recoding
    print(table(dcas[,c('dem.educ.attain',paste0('educ',i))]))
}
# educ_names <- levels(dcas$dem.educ.attain)
# educ_names[1] <- paste0("\\emph{Educational Attainment}&&\\\\", educ_names[1])

dcas$inc <- dcas$dem.income.cat4
inc_dummies <- paste0('inc',1:4)
dcas[,inc_dummies] <- lapply(1:4,
        function(i) {unclass(dcas$dem.income.cat4)==i})
for(i in 1:4) { ## Check recoding
    print(table(dcas[,c('dem.income.cat4',paste0('inc',i))]))
}
texcmds[['miinc']] <- sum(is.na(dcas$dem.income.cat4))
texcmds[['miedu']] <- sum(is.na(dcas$dem.educ.attain))
# inc_names <- sanitize(levels(dcas$dem.income.cat4))
# inc_names[1] <- paste0("\\emph{Income}&&\\\\", inc_names[1])
```

```{r nhood-variables}
dcas$nhdyrs <- as.numeric(as.character(dcas$q4)) - 10 ## Center at 10 years
dcas$nhdyrsc <- scale(dcas$nhdyrs, scale=FALSE)
qplot(dcas$nhdyrsc)

dcas$nhdsize[unclass(dcas$nhd.size)%in%c(1,2)] <- '1-9 blocks'
dcas$nhdsize[unclass(dcas$nhd.size)%in%c(3,4)] <- '10-50 blocks'
dcas$nhdsize[unclass(dcas$nhd.size)==5] <- '>50 blocks'
dcas$nhdsize <- factor(dcas$nhdsize, 
                        levels=c('1-9 blocks', '10-50 blocks', '>50 blocks'))
dcas$nhdsize <- relevel(dcas$nhdsize, ref='1-9 blocks')
table(dcas[,c('nhd.size', 'nhdsize')], useNA='always') ## Check recoding
```
