```{r setup-analysis-environment}
rm(list=ls())
load('../data/dcassvy.Rdata')
texcmds[['Rversion']] <- paste(R.version$major, R.version$minor, sep='.')
source('broom_mi.R') ## Saves multiple imputation
                     ## objects for use with tidyverse
```

```{r descriptives}
desc <- function(dat, x) {
    print(x)
    res <- summary(MIcombine(with(dat, svymean(as.formula(paste0('~',x))))))
    return(res[,1:2])
}

make.desc <- function(dat) {
    ## Independent variable (race)
    d <- desc(dat, 'dem.race')
    print(d)
    
    ## Demographic variables
    d <- rbind(d, desc(dat, 'age'))
    print(d)
    d['age','results'] <- d['age','results'] + 50
    print(d)
    d <- rbind(d, desc(dat, 'forborn')[2,])
    d <- rbind(d, desc(dat, 'man')[2,])
    d <- rbind(d, desc(dat, 'kids')[2,])
    d <- rbind(d, desc(dat, 'married')[2,])
    
    ## SES variables
    d <- rbind(d, desc(dat, 'educ')[c(2,1,3:5),])
    
    ## Neighborhood experience variables
    d <- rbind(d, desc(dat, 'nhdyrs'))
    d['nhdyrs','results'] <- d['nhdyrs','results'] + 10
    d <- rbind(d, desc(dat, 'nhdsize'))
    
    # return(d)
}
d <- make.desc(dcassvy) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='api'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='black'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='latino'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='white'))) %>%
    round(2) 
continuous_vars <- grep('age|nhdyrs',rownames(d), perl=TRUE)
d[1:4, 3:10] <- ""
d[-continuous_vars,c(2,4,6,8,10)] <- ""

tbl.names <- c(
    '\\emph{Race}&&\\\\White', 'Asian', 'Black', 'Latinx\\vspace{1em}', 
    '\\emph{Demographics}&&\\\\Age', 'Foreign Born', 'Man', 'Children present',
    'Married\\vspace{1em}',
    '\\emph{Education}&&\\\\Less than H.S.','H.S. or G.E.D.','Some college', 
    'Bachelor\'s degree', 'Professional degree\\vspace{1em}',
    '\\emph{Neighborhood Experience}\\\\Years in Neighborhood', 
    'Perceived neighborhood size\\\\1-9 blocks',  '10-50 blocks', 
    '>50 blocks'
)

d <- data.frame(tbl.names, d)
descriptive_tbl <- as.table(as.matrix(d))
colnames(descriptive_tbl) <- c('Variable', rep(c('Mean', 'S.D.'),5))

fname <- 'tables/descriptives.tex'
print.xtable(xtable(descriptive_tbl,
                    caption='Means and standard deviations of independent and control variables',
                    align=c('l','l', rep(c('R{.4in}','R{.4in}'), 5)), 
                    label='tab:descriptives'),
             booktabs = TRUE,
             floating.environment = 'sidewaystable',
             caption.placement = 'top',
             include.rownames = FALSE,
             file = fname,
             sanitize.text.function = identity,
             timestamp = '')

colsets <-  paste(
      '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Total Sample}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Asians}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Blacks}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Latinxs}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Whites}} \\\\'
)
tbltxt <- readLines(fname)
ruleline <- grep('toprule', tbltxt)
tbltxt <- c(tbltxt[1:ruleline], colsets, tbltxt[(ruleline+1):length(tbltxt)])
writeLines(tbltxt, fname)
```

```{r reporting-functions}
source('report_models.R')
source('make_predictions.R')
get_aic <- function(d, m=5){ ## Record mean and between-model variance of AIC
    aics <- sapply(d, function(x) x$aic)
    return(list(mean=mean(aics), var=var(aics)))
}

MIcombine_aic <- function(m) { ## Combines imputations, including AIC
    aic <- get_aic(m)
    mi <- MIcombine(m)
    mi$aic <- aic
    return(mi)
}

```

```{r define-models}
m1 <- 'dem.race + sample_tract '
m2 <- paste0(m1, '+ age + forborn + man + kids + married +
                 educ')
m3 <- paste0(m2, '+ nhdyrs + nhdsize')
m4 <- sub('dem\\.race \\+ ','',m3)
```

```{r tract-clustering}
## Describe clustering of respondents within tracts
tract_Ns <- sapply(unique(dcas$sample_tract), 
                   function(x){nrow(dcas[dcas$sample_tract==x,])})
num_quads <- length(tract_Ns)
texcmds[['oneresp']] <- sum(tract_Ns==1)
texcmds[['medNpertract']] <- median(tract_Ns[tract_Ns>1])
texcmds[['maxNpertract']] <- max(tract_Ns)
tract_Nfreq <- as.data.frame(table(tract_Ns))
tract_Ns_hist <- ggplot(tract_Nfreq, aes(x=Freq)) + 
    geom_histogram(binwidth=1) +
    scale_x_continuous(breaks=1:19, labels=1:19) +
    labs(title="Distribution of respondents per tract",
         subtitle="Respondents living in quadrivial tracts, 2016 DCAS")
ggsave('images/distribution-of-tract-sample-sizes.png',plot=tract_Ns_hist,
       height=3, width=4, units='in')
```

```{r satisfied-mean}
mean_satisfied <- MIcombine(with(dcassvy,svymean(~satisfied)))
texcmds[['meansatisfied']] <- round(coef(mean_satisfied),2)[[1]]*100
satisfied_byrace <- MIcombine(
    with(dcassvy,svyby(~satisfied, ~I(dem.race), svymean))) %>%
    coef() %>% round(2)*100
texcmds[['apisatisfied']] <- round(satisfied_byrace[['api']])
texcmds[['nhbsatisfied']] <- round(satisfied_byrace[['black']])
texcmds[['hspsatisfied']] <- round(satisfied_byrace[['latino']])
texcmds[['nhwsatisfied']] <- round(satisfied_byrace[['white']])
```


```{r satisfied-analysis, warning=FALSE, results='hide'}
## Satisfaction Model 0: Only fixed effects (not reported)
m0_sat <- with(dcassvy,
               svyglm(satisfied ~ sample_tract), family=binomial)
m0_sat <- MIcombine_aic(m0_sat)

## Satisfaction Model 1: Race & Fixed Effects
m1_sat <- with(dcassvy,
               svyglm(as.formula(paste('satisfied ~',m1)), family=binomial))
m1_sat_ame <- lapply(seq_along(m1_sat), get.margins, m1_sat) %>%
    calculate.pvals() 
ame_names <- paste0('satame1',c('api','black','latino'))
texcmds[ame_names] <- round(abs(m1_sat_ame$AME_link$AMEmi),3)*100

sat_pred_m1 <- MIpredict(m1_sat)
sat_pred_m1$race <- levels(dcas$dem.race)
sat_pred_m1$model <- 'Race only'

m1_sat <- MIcombine_aic(m1_sat)

## Satisfaction Model 2: Race & Demographic Controls (not reported)
m2_sat <- with(dcassvy, svyglm(as.formula(paste('satisfied ~', m2)),
                               family=binomial))
m2_sat <- MIcombine_aic(m2_sat)

## Satisfaction Model 3: Full Model
m3_sat <- with(dcassvy, svyglm(as.formula(paste('satisfied ~', m3)), 
                               family=binomial))
m3_sat_ame <- lapply(seq_along(m3_sat), get.margins, m3_sat) %>%
    calculate.pvals()
ame_names <- paste0('satame3',c('api','black','latino'))
texcmds[ame_names] <- round(abs(m3_sat_ame$AME_link$AMEmi),3)*100

## Report values of Wald test of change in model fit for model 
## not including race
m3_sat_racewald <- lapply(m3_sat, regTermTest, test.terms=~dem.race, df=NULL)
sat_wald_F <- summary(sapply(m3_sat_racewald, function(x) x$Ftest))
sat_wald_p <- summary(sapply(m3_sat_racewald, function(x) x$p))
texcmds[['satWaldF']] <- round(sat_wald_F['Mean'], 2)[[1]]
texcmds[['satWaldpMin']] <- round(sat_wald_p['Min.'], 2)[[1]]
texcmds[['satWaldpMax']] <- round(sat_wald_p['Max.'], 2)[[1]]

sat_pred_m3 <- MIpredict(m3_sat)
sat_pred_m3$race <- levels(dcas$dem.race)
sat_pred_m3$model <- 'Race + controls'

m3_sat <- MIcombine_aic(m3_sat)
texcmds[['satnhdsize']] <- round(exp(coef(m3_sat)['nhdsize10-50 blocks']),2)[[1]]

## Satisfaction Model 4: Full Model Without Race
m4_sat <- with(dcassvy, svyglm(as.formula(paste('satisfied ~', m4)),
                                family=binomial))
m4_sat <- MIcombine_aic(m4_sat)

```

```{r report-satisfaction-results, echo=TRUE, include=TRUE}
regression_labels <- c('Asian','Black','Latinx',
                       'Age','Foreign Born','Male',
                       'Children Present', 'Married',
                       levels(dcas$dem.educ.attain)[c(1,3:5)],
                       # levels(dcas$dem.income.cat4)[c(1,3:4)],
                       'Years in neighborhood',
                       '10-50 blocks', '>50 blocks')
sat_tbl <- report_models(m1_sat, m3_sat, m4_sat, reglabels=regression_labels,
                         caption=paste0('Estimated coefficients predicting ',
                                        ' neighborhood satisfaction'),
                         label='tab:satisfaction')
sat_tbl
cat(to_latex(sat_tbl), file='tables/satisfaction.tex')
```

```{r plot-satisfaction}

sat_plt <- plot.predictions(sat_pred_m1, sat_pred_m3) +
    theme_bw() + theme(legend.position='none')

sat_plt
ggsave('images/satisfied.png', plot=sat_plt, 
       width=6.75, units='in')
```


```{r ame-satisfaction}


diff_m1 <- max(sat_pred_m1['p']) - min(sat_pred_m1['p'])
texcmds[['maxdiffone']] <- round(diff_m1,2)*100
diff_m3 <- max(sat_pred_m3['p']) - min(sat_pred_m3['p'])
texcmds[['maxdiffthree']] <- round(diff_m3,2)*100
```
