```{r setup-analysis-environment}
rm(list=ls())
load('../data/dcassvy.Rdata')
texcmds[['Rversion']] <- paste(R.version$major, R.version$minor, sep='.')
source('broom_mi.R') ## Saves multiple imputation
## objects for use with tidyverse
```

```{r descriptives}
desc <- function(dat, x) {
    print(x)
    res <- summary(MIcombine(with(dat, svymean(as.formula(paste0('~',x))))))
    return(res[,1:2])
}

make.desc <- function(dat) {
    ## Independent variable (race)
    d <- desc(dat, 'dem.race')
    print(d)

    ## Demographic variables
    d <- rbind(d, desc(dat, 'age'))
    d['age','results'] <- d['age','results'] + 50
    d <- rbind(d, desc(dat, 'forborn')[2,])
    d <- rbind(d, desc(dat, 'man')[2,])
    d <- rbind(d, desc(dat, 'kids')[2,])
    d <- rbind(d, desc(dat, 'married')[2,])

    ## SES variables
    d <- rbind(d, desc(dat, 'educ')[c(2,1,3:5),])

    ## Neighborhood experience variables
    d <- rbind(d, desc(dat, 'nhdyrs'))
    d['nhdyrs','results'] <- d['nhdyrs','results'] + 10
    d <- rbind(d, desc(dat, 'nhdsize'))

    # return(d)
}
d <- make.desc(dcassvy) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='api'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='black'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='latino'))) %>%
    cbind(make.desc(subset(dcassvy, dem.race=='white'))) %>%
    round(2)
continuous_vars <- grep('age|nhdyrs',rownames(d), perl=TRUE)
d[1:4, 3:10] <- ""
d[-continuous_vars,c(2,4,6,8,10)] <- ""

tbl.names <- c(
    '\\emph{Race}&&\\\\White', 'Asian', 'Black', 'Latinx\\vspace{1em}',
    '\\emph{Demographics}&&\\\\Age', 'Foreign Born', 'Man', 'Children present',
    'Married\\vspace{1em}',
    '\\emph{Education}&&\\\\Less than H.S.','H.S. or G.E.D.','Some college',
    'Bachelor\'s degree', 'Professional degree\\vspace{1em}',
    '\\emph{Neighborhood Experience}\\\\Years in Neighborhood',
    'Perceived neighborhood size\\\\1-9 blocks',  '10-50 blocks',
    '>50 blocks'
)

d <- data.frame(tbl.names, d)
descriptive_tbl <- as.table(as.matrix(d))
colnames(descriptive_tbl) <- c('Variable', rep(c('Mean', 'S.D.'),5))

fname <- 'tables/descriptives.tex'
print.xtable(xtable(descriptive_tbl,
                    caption='Means and standard deviations of independent and control variables',
                    align=c('l','l', rep(c('R{.4in}','R{.4in}'), 5)),
                    label='tab:descriptives'),
             booktabs = TRUE,
             floating.environment = 'sidewaystable',
             caption.placement = 'top',
             include.rownames = FALSE,
             file = fname,
             sanitize.text.function = identity,
             timestamp = '')

colsets <-  paste(
    '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Total Sample}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Asians}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Blacks}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Latinxs}}'
    , '& \\multicolumn{2}{p{.8in}}{\\centering \\strong{Whites}} \\\\'
)
tbltxt <- readLines(fname)
ruleline <- grep('toprule', tbltxt)
tbltxt <- c(tbltxt[1:ruleline], colsets, tbltxt[(ruleline+1):length(tbltxt)])
writeLines(tbltxt, fname)
```
