```{r familiarity-analysis}
m3_srch <- sub('\\+ nhdyrs.+$', '', m3) # Eliminate nhood perceptions variables

nhd.model <- function(nhd, dim, model) {
    nhdvar <- paste0('nhd.srch.', nhd, '.', dim)
    f <- as.formula(paste0(nhdvar, ' ~ ', model))
    ## Removed whether respondents indicated that they lived in the community 
    ## because so few indicated living in the neighborhoods when broken out by
    ## race
    # f <- as.formula(paste0(nhdvar, ' ~ ', model, ' + nhd.srch.', nhd, '.live'))
    return(with(dcassvy, svyglm(f, family=binomial)))
}

srch.mean <- function(nhd, dim) {
    x <- paste0('nhd.srch.', nhd, '.', dim)
    sum <- summary(
        MIcombine(with(dcassvy, svymean(as.formula(paste0('~',x))))))
    return(sum$results[2])
}

quad.nhoods <- c('herndon', 'germantown', 'wheaton')
Quad.Nhoods <- c('Herndon', 'Germantown', 'Wheaton')

## Calculate averages of each dimension for each community and report to 
## LaTeX commands
dk_means <- sapply(quad.nhoods, srch.mean, 'dk')
ff_means <- sapply(quad.nhoods, srch.mean, 'ff')
cons_means <- sapply(quad.nhoods, srch.mean, 'cons')
nc_means <- sapply(quad.nhoods, srch.mean, 'nc')

texcmds[paste0('dk', quad.nhoods)] <- round(dk_means, 2) * 100
texcmds[paste0('ff', quad.nhoods)] <- round(ff_means, 2) * 100
texcmds[paste0('cons', quad.nhoods)] <- round(cons_means, 2) * 100
texcmds[paste0('nc', quad.nhoods)] <- round(nc_means, 2) * 100

## Don't Know
m1_dk <- lapply(quad.nhoods, nhd.model, 'dk', m1)
names(m1_dk) <- quad.nhoods
m1_dk_pred <- lapply(m1_dk, MIpredict)
m1_dk <- lapply(m1_dk, MIcombine_aic)

m3_dk <- lapply(quad.nhoods, nhd.model, 'dk', m3_srch)
names(m3_dk) <- quad.nhoods
m3_dk_pred <- lapply(m3_dk, MIpredict)
m3_dk <- lapply(m3_dk, MIcombine_aic)

## Friends & Family
m1_ff <- lapply(quad.nhoods, nhd.model, 'ff', m1)
names(m1_ff) <- quad.nhoods
m1_ff_pred <- lapply(m1_ff, MIpredict)
m1_ff <- lapply(m1_ff, MIcombine_aic)

m3_ff <- lapply(quad.nhoods, nhd.model, 'ff', m3_srch)
names(m3_ff) <- quad.nhoods
m3_ff_pred <- lapply(m3_ff, MIpredict)
m3_ff <- lapply(m3_ff, MIcombine_aic)
```

```{r report-familiarity-results, echo=TRUE, include=TRUE}
know_tbl <- report_models(m3_dk[[1]], m3_dk[[2]], m3_dk[[3]],
                         reglabels=regression_labels,
                         caption='Estimated coefficients predicting unfamiliarity with selected multiethnic communities',
                         label='tab:knowledge')

rmv <- grep('Neighborhood perceptions|>50 blocks', know_tbl$names, perl=TRUE)

know_tbl[1, ] <-c('','Herndon','~~~~Germantown','~~~~~~Wheaton')
insert_column(know_tbl, after=2, rep(' ', nrow(know_tbl)))
know_tbl <- know_tbl[-1*seq(from=rmv[1], to=rmv[2])] %>%
    # insert_row(c('','Herndon','Germantown','Wheaton'), after=0) %>%
    set_bottom_border(row=1,col=everywhere, value=1) %>%
    set_bottom_border(row=final(1), col=everywhere, value=1) %>%
    # set_top_border(row=2,col=everywhere, value=0) %>%
    set_left_padding(row=1, col=final(2), value=15)

know_tbl
cat(to_latex(know_tbl), file='tables/knowledge.tex')

## Replace LaTeX formatted tildas with unformatted tildas to reduce
## crowding of text in first row of table
txt <- readLines('tables/knowledge.tex')
writeLines(gsub('\\\\~\\{\\}', '~', txt), 'tables/knowledge2.tex')
```









```{r}
# know_tbl[1, 2:4] <- Quad.Nhoods
# 
# ## Remove rows labeling neighborhood perception data
# rmv <- c(which(know_tbl$names=='Neighborhood perceptions')) %>%
#     append(as.vector(
#         unique(sapply(c(0,1), function(x) {
#             which(know_tbl$names %in% c('Years in neighborhood', 
#                                         '10-50 blocks', '>50 blocks'))+x
# }))))
# know_tbl <- know_tbl[-rmv, ] 
# know_tbl <- set_bottom_border(know_tbl,
#     row=nrow(know_tbl)-1, col=everywhere, value=1) %>%
#     set_col_width(2:4, '12')
# know_tbl
# 
# know_tbl <- set_align(know_tbl, row=everywhere, col=2:4, value='right')
# 
# cat(to_latex(know_tbl), file='tables/knowledge.tex')
# 
# 
# 
# know_tbl <- huxreg(append(m3_dk, m3_ff))
# know_tbl[seq(4,9,2),1] <- regression_labels[1:3]
# know_tbl[1,] <- c('', rep(c('\tHerndon', '   German.','   Wheaton'), 2))
# know_tbl <- know_tbl[c(1:9, nrow(know_tbl)),] %>%
#     insert_column(rep('',10),after=4) %>%
#     insert_row(c('',
#                  'Don\'t know', '', '', '',
#                  'Friends and family','',''), after=0) %>%
#     merge_cells(c(1:1),c(2:4)) %>% merge_cells(c(1:1),c(6:8)) %>%
#     set_align(1, everywhere, 'center') %>%
#     set_bottom_border(row=everywhere, col=everywhere, value=0) %>%
#     set_bottom_border(row=2, col=everywhere, value=1) %>%
#     set_bottom_border(row=where(know_tbl$names=='Latinx')+2,
#                       col=everywhere, value=1) %>%
#     set_top_border(row=everywhere, col=everywhere, value=0) %>%
#     set_top_border(row=1, col=everywhere, value=1) %>%
#     set_caption('Estimated coefficients predicting knowledge and acquaintances in selected multiethnic communities') %>%
#     set_label('tab:knowledge') 
# 
# know_tbl
# cat(to_latex(know_tbl), file=fname)
# 
# tbltxt <- readLines(fname)
# tbltxt <- gsub('\\{table\\}', '{sidewaystable}', tbltxt)
# tbltxt <- gsub('\\multicolumn\\{1\\}\\{c', '\\multicolumn{1}{R{6.25em}', tbltxt)
# tbltxt <- gsub('\\\\centering\\s+([H|G|W|\\\\])','\\1',tbltxt)
# writeLines(tbltxt, fname)

```

```{r consider-analysis}
m1_con <- lapply(quad.nhoods, nhd.model, 'cons', m1)
names(m1_con) <- quad.nhoods
m1_con_ame <- lapply(m1_con, function(x) calculate.pvals(lapply(seq_along(x), get.margins, x)))
m1_con_pred <- lapply(m1_con, MIpredict)
m1_con <- lapply(m1_con, MIcombine_aic)
texcmds[['conameonelatinogerman']] <- round(
    m1_con_ame$germantown$AME_resp[['latino']], 2)*100
texcmds[['conameonelatinowheaton']] <- round(
    m1_con_ame$wheaton$AME_resp[['latino']], 2)*100
texcmds[['conameoneblackwheaton']] <- round(
    m1_con_ame$wheaton$AME_resp[['black']], 2)*100
texcmds[['conameoneblackwheatonp']] <- round(
    m1_con_ame$wheaton$AME_link$pmi[2], 2)


m3_con <- lapply(quad.nhoods, nhd.model, 'cons', m3_srch)
names(m3_con) <- quad.nhoods
m3_con_ame <- lapply(m3_con, function(x) calculate.pvals(lapply(seq_along(x), get.margins, x)))
m3_con_pred <- lapply(m3_con, MIpredict)
m3_con <- lapply(m3_con, MIcombine_aic)
```

```{r report-consider-results}
## Label lives in community variable to be the same across models
fname <- 'tables/consider.tex'
cons_labels <- regression_labels[1:(length(regression_labels)-3)]
cons_tbl <- report_models(m1_con$herndon, m3_con$herndon, 
                          m1_con$germantown, m3_con$germantown,
                          m1_con$wheaton, m3_con$wheaton, 
                          reglabels=cons_labels,
                          caption=paste0("Estimated coefficients predicting ",
                                         "whether person would consider moving ",
                                         "to the community"),
                          label='tab:consider')
cons_tbl <- cons_tbl[
    -1*grep('Neighborhood perceptions|AIC', cons_tbl$names)] %>%
    insert_row(c('','Herndon','','Germantown','','Wheaton',''), after=0) %>%
    merge_cells(1:1,2:3) %>% merge_cells(1:1,4:5) %>% merge_cells(1:1,6:7) %>%
    set_align(1, everywhere, 'center') %>%
    set_bottom_border(row=1,col=everywhere, value=0) %>%
    set_top_border(row=final(1), col=everywhere, value=1) %>%
    set_top_border(row=2,col=everywhere, value=0) %>%
    set_left_padding(row=1, col=final(2), value=15) 
cons_tbl[2,] <- c('',sapply(rep(c(1,2),3),function(x) paste0('(',x,')')))
cons_tbl
cat(to_latex(cons_tbl), file=fname)
```


```{r not-consider-analysis}
m1_nc <- lapply(quad.nhoods, nhd.model, 'nc', m1)
names(m1_nc) <- quad.nhoods
m1_nc_pred <- lapply(m1_nc, MIpredict)
m1_nc <- lapply(m1_nc, MIcombine_aic)

m3_nc <- lapply(quad.nhoods, nhd.model, 'nc', m3_srch)
names(m3_nc) <- quad.nhoods
m3_nc_pred <- lapply(m3_nc, MIpredict)
m3_nc <- lapply(m3_nc, MIcombine_aic)
```

```{r report-non-consider-results}
fname <- 'tables/notconsider.tex'
nc_tbl <- report_models(m1_nc$herndon, m3_nc$herndon, 
                        m1_nc$germantown, m3_nc$germantown,
                        m1_nc$wheaton, m3_nc$wheaton,
                        reglabels=cons_labels,
                        caption=paste0("Estimated coefficients predicting ",
                                       "whether person would never consider ",
                                       "moving to the community"),
                        label='tab:notconsider')
nc_tbl <- nc_tbl[
    -1*grep('Neighborhood perceptions|AIC', nc_tbl$names)] %>%
    insert_row(c('','Herndon','','Germantown','','Wheaton',''), after=0) %>%
    merge_cells(1:1,2:3) %>% merge_cells(1:1,4:5) %>% merge_cells(1:1,6:7) %>%
    set_align(1, everywhere, 'center') %>%
    set_bottom_border(row=1,col=everywhere, value=0) %>%
    set_top_border(row=final(1), col=everywhere, value=1) %>%
    set_top_border(row=2,col=everywhere, value=0) %>%
    set_left_padding(row=1, col=final(2), value=15)
nc_tbl[2,] <- c('',sapply(rep(c(1,2),3),function(x) paste0('(',x,')')))
nc_tbl
cat(to_latex(nc_tbl), file=fname)
```


```{r}
writeLines(sapply(names(texcmds), function(x) paste0(
    '\\newcommand{\\', x, '}{', texcmds[x], '}')
    ), con='values_to_tex.tex')

```
