# Notes
Correlation of education and income: 

```{r, echo=TRUE, include=TRUE}
ggplot(dcas, aes(x=dem.income.cat4,y=dem.educ.attain)) + geom_jitter()
```

## Notes from Writing Group April 4, 2019

### Comments

David

:   * Like the setup on the front end (but didn't have a whole lot of time to read it)
    * The graphs with point estimates and confidence intervals were helpful "to prove the null"
    * Examine whether a joint F-test for significance of the race variables together provide significant improvement in fit; alternatively, use the AIC & BIC values to run the full model without race variable and then with race variable
    * **Add fixed effects** 
        * Have fixed effects in the models the entire time
        * Used fixed effects to frame the method as being about comparing residents of different races *in the same neighborhood* 
        
Alex

:   * Was left with the question, so what? Bring out that this fits with my research showing that white acceptance of non-white neighbors is insufficient, they need to seek diverse neighborhoods for integration to persist
    * I am selecting on people who stayed, so these would be the whites *most* inclined to be satisfied with their neighborhoods; bring out that in most of these neighborhoods, whites are still the majority -- so if they *are* selected, there is still a large proportion of whites satisfied living in multiethnic neighborhoods
    * Subset by parental status (link to Ann Owens' ASR paper)
    * Point out that this study is unique to some degree to DC, which is a type of multiethnic metropolitan area that is often overlooked (it's not a black/white city, which are now the anomolies, places like DC are the future)

### Potential Journals

* *Demography* especially with Mark Hayward as the editor
* Possibly worth trying at a general sociology journal like *Social Forces*; subject-matter also fits at *Social Problems* and *Social Science Research* 
* *Urban Affairs Review*
    
### Future Directions

* Do white conservatives look different than white liberals? Maybe find a political scientist interested in neighborhoods to collaborate
* Look at paper by Ryan Enos about how the demolition of public housing shifted whites' political views
