# Supplement

## Data Construction
### Correlation of education and income:

```{r education-income-correlation, echo=TRUE, include=TRUE}
ggplot(dcas, aes(x=dem.income.cat4,y=dem.educ.attain)) + geom_jitter()
```

## Between Neighborhood Analysis

**TODO: Analyze regression of satisfaction in DCAS 2018 including entropy or HHI as a covariate in the model to test relationship of diversity to satisfaction.**

## Neighborhood Change Analysis
### Multinomial Logistic Regression of Neighborhood Change Questions
```{r improvement-analysis-multinomial}
library(svrepmisc)
des <- as.svrepdesign(svy$designs[[1]], type="bootstrap" , replicates=250)
m3m_bet <- svymultinom(as.formula(paste('nhd.change3 ~', m3)),
                       design = des)
tbl <- tidy(m3m_bet)[1:8,] %>%
    mutate(star = if_else(p.value < .001, '***',
                          if_else(p.value < .01, '**',
                                  if_else(p.value < 0.05, '*', ''))))
vals <- function(i) {
    c(sprintf("%5.3f", tbl[i,2]), sprintf("(%5.3f)", tbl[i,3]))
}

df <- tibble(
    Variable = c("Intercept", "", "Asian", "", "Black", "", "Latinx", ""),
    Better = c(sapply(seq(1, 7, 2), vals)),
    ` `  = c(sapply(tbl[seq(1, 7, 2), 6], c, "")),
    Worse  = c(sapply(seq(2, 8, 2), vals)),
    `  `  = c(sapply(tbl[seq(2, 8, 2), 6], c, ""))
)

kable(df, align = 'lrlrl', format = 'pandoc')
```

