---
title: "Replication File and Supplemental Analyses for 'Neighborhood Satisfaction in Multiracial Neighborhoods'"
author: "Michael Bader"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    config:
      toc:
        collapse: subsubsection
        scroll_highlight: yes
  # bookdown::pdf_book:
  #   keep_tex: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, include=TRUE, message=FALSE, cache = FALSE)
```


# Set Up

Clear all objects out of R. 
```{r rm, message=FALSE}
rm(list=ls())
```

Load the libraries necessary for the analysis and presentation of data. 
```{r libraries, message=FALSE, warning=FALSE}
library(Amelia)
library(broom)
library(ggplot2)
library(huxtable)
library(knitr)
library(kableExtra)
library(margins)
library(mitools)
library(survey)
library(tidyverse)
library(xtable)

```

**R Version.** The analyses were built with `r R.version.string`, as reported on page 13 of the manuscript.

Create a list to hold results that will be reported to LaTeX later. 
```{r tex-commands}
texcmds <- list()
```

